KansasCityWomeninTechnology/cocktails-site

- package-lock.json
- package.json
I couldn't npm install. updating cli version fixed node-sass problems. 😒 
I have Node v10. I tried both npm v6 and npm v5.8 and still ran into the problem figured updating cli dep was the best way to fix.
> update deps. node-sass strikes again!

- angular.json
- package-lock.json
- package.json
- src/app/contact/contact.component.scss
- src/app/financial-aid/financial-aid.component.html
- src/app/hero/hero.component.scss
- src/app/home/home.component.scss
- src/app/home/home.component.ts
I forgot that I said I would update asset references. I added assets to the styles path options in the cli config so we won't have to use rel paths for referencing images from scss files as well.
> Update dep and asset reference change

- src/app/resources/resources.component.html
- src/app/resources/resources.component.ts
I know it's not difficult to do, but having the bitly links make it easier for newbies like me. Was super quick so I thought I'd throw it out here.
> Quick tweak to make it easier to activate links

- package.json
- src/app/home/home.component.html
- src/app/home/home.component.ts
Hopefully makes things easier and less places to remember to update. Should just be able to bump the session index in the array. 
I changed the date format so that we can use the DatePipe for formatting. 
Threw the `--aot` flag on `ng serve` so that serving mimics build compilation.
> Quick tweak to make upcoming session pull from topics list

- src/data/data.ts
Update signup section for August
- Switch session signup
- Update venue: August is back at The Nerdery
> That was Easy

- src/data/data.ts
I did this from my cell phone. I love you Github <3
Also Alisa TY for making this so easy!
> Update data.ts for August links

- package-lock.json
- package.json
- src/app/home/home.component.html
- src/app/home/home.component.scss
- Update deps
- Add rideshare text to cocktail section
- Update link colors to brand
> Cleanup & rideshare addition

- src/data/sessions.ts
Updating the session dates due to the cancelled Jan session pushing schedule back 1 month.
> update schedule dates

- src/data/sessions.ts
> Update and activate links

- src/data/sessions.ts
as opposed to iframes, which I just did and didn't realize were different [facepalm emoji]
> Add regular links for july-aug sessions

- package-lock.json
- src/app/app.component.html
- src/app/contact/contact.component.html
- src/app/footer/footer.component.html
- src/app/hero/hero.component.html
- src/app/home/home.component.html
- src/styles/_utilities.scss
- src/styles/styles.scss
Fix accessibility and ADA issues within main template, contact, footer, hero, home, and add screen-reader-only class for content to be read to screen readers but not seen visually
> Fix various accessibility and ADA issues

- src/app/app.module.ts
- src/app/mentor-form/_mentor-form.component.theme.scss
- src/app/mentor-form/mentor-form.component.html
- src/app/mentor-form/mentor-form.component.scss
- src/app/mentor-form/mentor-form.component.spec.ts
- src/app/mentor-form/mentor-submit-response.component.spec.ts
- src/styles/_cocktails-material-palette.scss
- src/styles/_material-theme.scss
- src/styles/styles.scss
This is for mentor signup form. Looks like this
> Add inline validation to input and disable submit until valid

- package-lock.json
- package.json
- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/app/hero/hero.component.html
- src/app/hero/hero.component.scss
- src/app/home/home.component.ts
- src/app/nav/nav.component.html
- src/app/nav/nav.component.ts
- src/app/shared/scroll-to-fragment.directive.spec.ts
- src/app/shared/scroll-to-fragment.directive.ts
I'll let this sit for a few days so people can inspect
> Fix router so that navigation backwards using fragments on site works

- src/app/home/home.component.html
- src/data/sessions.ts
* Add dates for 2020
* Cleanup Feb 2019 date
> 2020 Promotion

- src/app/home/signup/signup.component.html
> update signup message

- src/app/home/signup/signup.component.html
- src/data/heroes.ts
- src/data/sessions.ts
Update the signup section to list 2020 online events.
> 2020 event update

- src/app/contact/contact.component.html
delete h5 tag
try br tag to see if needed and it is not required for styling
deleting h5 tag provided an alignment correction of contact us
> remove unnecessary header tag (#119)

- src/app/app.component.router.spec.ts
- src/app/app.component.spec.ts
- src/app/home/signup/signup.component.spec.ts
- src/app/nav/nav.component.spec.ts
- src/app/nav/nav.component.ts
Fixes issue (#107)
☑︎ Verified app loads and loads the following:
- src/app/app.component.ts 
- app.component.router.spec.ts
- nav.component.specs.ts
- nav.component.ts
- signup.component.specs.ts
- signup.component.router.specs.ts
☑︎ Ran lint and verified lint errors are addressed
☑︎ Ran tests
> Fixing lint errors issue (#115)

- src/app/contact/contact.component.html
> updated link to https

- src/app/hero/hero.component.spec.ts
- src/app/hero/hero.component.ts
addresses issue #111 - There are lint errors in HeroComponent that need to be fixed
1. src/app/hero/hero.component.spec.ts:10:14
2. src/app/hero/hero.component.ts:12:3
> issue 111 changes made

- src/app/resources/resources.component.spec.ts
- src/app/resources/resources.component.ts
- src/app/resources/tools/tools.component.spec.ts
fixed lint errors in Resources and Tools components Issue #117
> Issue #117 : fixed lint errors in Resources and Tools components

- src/app/contact/contact.component.spec.ts
- src/app/contact/contact.component.ts
> fix lint errors in ContactComponent

- src/app/home/cocktails/cocktails.component.spec.ts
- src/app/home/code/code.component.spec.ts
- src/app/home/home.component.spec.ts
- src/app/home/mentor-form/mentor-form.component.spec.ts
- src/app/home/mentor-form/mentor-submit-response.component.spec.ts
- src/app/home/mentors/mentors.component.spec.ts
- src/app/shared/scroll-to-fragment.directive.spec.ts
Fixes #118 
Fixes #114 
Fixes #113
> fix a bunch of lint errors

- e2e/src/app.po.ts
> fix lint errors

- src/data/sessions.ts
> update worksheet link

- src/data/sessions.ts
> disable link

- src/data/sessions.ts
Adding Grid Garden as worksheet as that is what they will work on.
> amp adding june session and worksheet

- src/data/sessions.ts
update enabled slides and worksheet
> update enabled slides and worksheet - html only

- src/data/sessions.ts
Added March event to the C&C website
> Added March event

- src/data/heroes.ts
> VSProfile Add Nessa profile to director
